---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ububtu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-actions@v1
        with:
          user: ${{ secrets.DOCKERHUB_USER}}
          password: ${{ secrets.DOCKERHUB_TOKEN}}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"